### ISSUE TITLE
use the latest version of the apple jar

### ISSUE THREAD

**Issue by tofi86** [screamingfrog/Maven#1]
I believe there's a newer version of the `AppleJavaExtensions.jar`. The attached file is what I extracted from the last macOS which shipped this library in `/usr/share/java/Stubs/AppleJavaExtensions.jar`:

[usr-share-java-Stubs-AppleJavaExtensions.jar.zip](https://github.com/screamingfrog/Maven/files/1734804/usr-share-java-Stubs-AppleJavaExtensions.jar.zip)

This Jar also has classes `com.apple.eawt.FullScreen*` which support the full screen api of macOS.

Would you consider updating your maven repo here with this latest version?

Thanks!

**Comment by liamsharp** [comment]
Hi @tofi86 - apologies for the (very!) late reply on this, I missed the notification!

We don't plan on updating this I'm afraid as we don't use the extensions anymore for our application.
